In [1]:
from google.colab import files
uploaded=files.upload()

Saving employees_dataset.csv to employees_dataset.csv

In [17]:
import pandas as pd
df=pd.read_csv('employees_dataset.csv')
df

    empid             name   salary  years_of_experience  department
0    1001     Rahul Sharma  45000.0                  3.0          IT
1    1002      Priya Reddy  52000.0                  5.0          HR
2    1003       Amit Kumar  60000.0                  6.0     Finance
3    1004              NaN  48000.0                  2.0   Marketing
4    1005        Kiran Rao  55000.0                  4.0          IT
5    1006     Anjali Gupta  70000.0                  7.0  Operations
6    1007      Rohit Verma      NaN                  8.0     Finance
7    1008      Pooja Singh  50000.0                  3.0          HR
8    1009       Vikram Das  80000.0                  9.0         NaN
9    1010       Neha Joshi  53000.0                  5.0   Marketing
10   1011      Arjun Mehta  62000.0                  6.0  Operations
11   1012       Kavya Nair  47000.0                  2.0          HR
12   1013     Suresh Yadav  85000.0                  NaN     Finance
13   1014     Divya Kapoor  58000.0                  5.0          IT
14   1015      Manoj Reddy  68000.0                  7.0  Operations
15   1016       Meena Iyer  51000.0                  3.0   Marketing
16   1017      Rakesh Jain  90000.0                 11.0     Finance
17   1018  Shreya Kulkarni  54000.0                  5.0          HR
18   1019   Naveen Chandra  72000.0                  8.0          IT
19   1020      Asha Thomas  46000.0                  2.0   Marketing
20   1021       Tarun Babu  64000.0                  6.0  Operations
21   1022    Nisha Agarwal  59000.0                  5.0          IT
22   1023     Harish Kumar  78000.0                  9.0     Finance
23   1024      Deepika Roy  49500.0                  3.0          HR
24   1025     Varun Mishra  67000.0                  7.0  Operations
25   1026     Lakshmi Devi  52500.0                  4.0   Marketing
26   1027      Ajay Sharma  95000.0                 12.0          IT
27   1028      Bhavana Rao  61000.0                  6.0     Finance
28   1029     Chirag Patel  74000.0                  8.0  Operations
29   1030       Ishita Sen  48000.0                  2.0          HR
30   1002      Priya Reddy  52000.0                  5.0          HR
31   1006     Anjali Gupta  70000.0                  7.0  Operations
32   1011      Arjun Mehta  62000.0                  6.0  Operations

In [18]:
df.isna().sum()

empid                  0
name                   1
salary                 1
years_of_experience    1
department             1
dtype: int64

In [19]:
df["name"].fillna("Unknown", inplace=True)

/tmp/ipykernel_3761/2216678673.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace=True)

In [20]:
df

    empid             name   salary  years_of_experience  department
0    1001     Rahul Sharma  45000.0                  3.0          IT
1    1002      Priya Reddy  52000.0                  5.0          HR
2    1003       Amit Kumar  60000.0                  6.0     Finance
3    1004          Unknown  48000.0                  2.0   Marketing
4    1005        Kiran Rao  55000.0                  4.0          IT
5    1006     Anjali Gupta  70000.0                  7.0  Operations
6    1007      Rohit Verma      NaN                  8.0     Finance
7    1008      Pooja Singh  50000.0                  3.0          HR
8    1009       Vikram Das  80000.0                  9.0         NaN
9    1010       Neha Joshi  53000.0                  5.0   Marketing
10   1011      Arjun Mehta  62000.0                  6.0  Operations
11   1012       Kavya Nair  47000.0                  2.0          HR
12   1013     Suresh Yadav  85000.0                  NaN     Finance
13   1014     Divya Kapoor  58000.0                  5.0          IT
14   1015      Manoj Reddy  68000.0                  7.0  Operations
15   1016       Meena Iyer  51000.0                  3.0   Marketing
16   1017      Rakesh Jain  90000.0                 11.0     Finance
17   1018  Shreya Kulkarni  54000.0                  5.0          HR
18   1019   Naveen Chandra  72000.0                  8.0          IT
19   1020      Asha Thomas  46000.0                  2.0   Marketing
20   1021       Tarun Babu  64000.0                  6.0  Operations
21   1022    Nisha Agarwal  59000.0                  5.0          IT
22   1023     Harish Kumar  78000.0                  9.0     Finance
23   1024      Deepika Roy  49500.0                  3.0          HR
24   1025     Varun Mishra  67000.0                  7.0  Operations
25   1026     Lakshmi Devi  52500.0                  4.0   Marketing
26   1027      Ajay Sharma  95000.0                 12.0          IT
27   1028      Bhavana Rao  61000.0                  6.0     Finance
28   1029     Chirag Patel  74000.0                  8.0  Operations
29   1030       Ishita Sen  48000.0                  2.0          HR
30   1002      Priya Reddy  52000.0                  5.0          HR
31   1006     Anjali Gupta  70000.0                  7.0  Operations
32   1011      Arjun Mehta  62000.0                  6.0  Operations

In [21]:
df["department"] = df["department"].fillna(df["department"].mode()[0])

In [22]:
df

    empid             name   salary  years_of_experience  department
0    1001     Rahul Sharma  45000.0                  3.0          IT
1    1002      Priya Reddy  52000.0                  5.0          HR
2    1003       Amit Kumar  60000.0                  6.0     Finance
3    1004          Unknown  48000.0                  2.0   Marketing
4    1005        Kiran Rao  55000.0                  4.0          IT
5    1006     Anjali Gupta  70000.0                  7.0  Operations
6    1007      Rohit Verma      NaN                  8.0     Finance
7    1008      Pooja Singh  50000.0                  3.0          HR
8    1009       Vikram Das  80000.0                  9.0  Operations
9    1010       Neha Joshi  53000.0                  5.0   Marketing
10   1011      Arjun Mehta  62000.0                  6.0  Operations
11   1012       Kavya Nair  47000.0                  2.0          HR
12   1013     Suresh Yadav  85000.0                  NaN     Finance
13   1014     Divya Kapoor  58000.0                  5.0          IT
14   1015      Manoj Reddy  68000.0                  7.0  Operations
15   1016       Meena Iyer  51000.0                  3.0   Marketing
16   1017      Rakesh Jain  90000.0                 11.0     Finance
17   1018  Shreya Kulkarni  54000.0                  5.0          HR
18   1019   Naveen Chandra  72000.0                  8.0          IT
19   1020      Asha Thomas  46000.0                  2.0   Marketing
20   1021       Tarun Babu  64000.0                  6.0  Operations
21   1022    Nisha Agarwal  59000.0                  5.0          IT
22   1023     Harish Kumar  78000.0                  9.0     Finance
23   1024      Deepika Roy  49500.0                  3.0          HR
24   1025     Varun Mishra  67000.0                  7.0  Operations
25   1026     Lakshmi Devi  52500.0                  4.0   Marketing
26   1027      Ajay Sharma  95000.0                 12.0          IT
27   1028      Bhavana Rao  61000.0                  6.0     Finance
28   1029     Chirag Patel  74000.0                  8.0  Operations
29   1030       Ishita Sen  48000.0                  2.0          HR
30   1002      Priya Reddy  52000.0                  5.0          HR
31   1006     Anjali Gupta  70000.0                  7.0  Operations
32   1011      Arjun Mehta  62000.0                  6.0  Operations

In [24]:
df["salary"] = df["salary"].fillna(df["salary"].median())

In [25]:
df

    empid             name   salary  years_of_experience  department
0    1001     Rahul Sharma  45000.0                  3.0          IT
1    1002      Priya Reddy  52000.0                  5.0          HR
2    1003       Amit Kumar  60000.0                  6.0     Finance
3    1004          Unknown  48000.0                  2.0   Marketing
4    1005        Kiran Rao  55000.0                  4.0          IT
5    1006     Anjali Gupta  70000.0                  7.0  Operations
6    1007      Rohit Verma  59500.0                  8.0     Finance
7    1008      Pooja Singh  50000.0                  3.0          HR
8    1009       Vikram Das  80000.0                  9.0  Operations
9    1010       Neha Joshi  53000.0                  5.0   Marketing
10   1011      Arjun Mehta  62000.0                  6.0  Operations
11   1012       Kavya Nair  47000.0                  2.0          HR
12   1013     Suresh Yadav  85000.0                  NaN     Finance
13   1014     Divya Kapoor  58000.0                  5.0          IT
14   1015      Manoj Reddy  68000.0                  7.0  Operations
15   1016       Meena Iyer  51000.0                  3.0   Marketing
16   1017      Rakesh Jain  90000.0                 11.0     Finance
17   1018  Shreya Kulkarni  54000.0                  5.0          HR
18   1019   Naveen Chandra  72000.0                  8.0          IT
19   1020      Asha Thomas  46000.0                  2.0   Marketing
20   1021       Tarun Babu  64000.0                  6.0  Operations
21   1022    Nisha Agarwal  59000.0                  5.0          IT
22   1023     Harish Kumar  78000.0                  9.0     Finance
23   1024      Deepika Roy  49500.0                  3.0          HR
24   1025     Varun Mishra  67000.0                  7.0  Operations
25   1026     Lakshmi Devi  52500.0                  4.0   Marketing
26   1027      Ajay Sharma  95000.0                 12.0          IT
27   1028      Bhavana Rao  61000.0                  6.0     Finance
28   1029     Chirag Patel  74000.0                  8.0  Operations
29   1030       Ishita Sen  48000.0                  2.0          HR
30   1002      Priya Reddy  52000.0                  5.0          HR
31   1006     Anjali Gupta  70000.0                  7.0  Operations
32   1011      Arjun Mehta  62000.0                  6.0  Operations

In [26]:
df["years_of_experience"] = df["years_of_experience"].fillna(df["years_of_experience"].mean())

In [27]:
df

    empid             name   salary  years_of_experience  department
0    1001     Rahul Sharma  45000.0              3.00000          IT
1    1002      Priya Reddy  52000.0              5.00000          HR
2    1003       Amit Kumar  60000.0              6.00000     Finance
3    1004          Unknown  48000.0              2.00000   Marketing
4    1005        Kiran Rao  55000.0              4.00000          IT
5    1006     Anjali Gupta  70000.0              7.00000  Operations
6    1007      Rohit Verma  59500.0              8.00000     Finance
7    1008      Pooja Singh  50000.0              3.00000          HR
8    1009       Vikram Das  80000.0              9.00000  Operations
9    1010       Neha Joshi  53000.0              5.00000   Marketing
10   1011      Arjun Mehta  62000.0              6.00000  Operations
11   1012       Kavya Nair  47000.0              2.00000          HR
12   1013     Suresh Yadav  85000.0              5.65625     Finance
13   1014     Divya Kapoor  58000.0              5.00000          IT
14   1015      Manoj Reddy  68000.0              7.00000  Operations
15   1016       Meena Iyer  51000.0              3.00000   Marketing
16   1017      Rakesh Jain  90000.0             11.00000     Finance
17   1018  Shreya Kulkarni  54000.0              5.00000          HR
18   1019   Naveen Chandra  72000.0              8.00000          IT
19   1020      Asha Thomas  46000.0              2.00000   Marketing
20   1021       Tarun Babu  64000.0              6.00000  Operations
21   1022    Nisha Agarwal  59000.0              5.00000          IT
22   1023     Harish Kumar  78000.0              9.00000     Finance
23   1024      Deepika Roy  49500.0              3.00000          HR
24   1025     Varun Mishra  67000.0              7.00000  Operations
25   1026     Lakshmi Devi  52500.0              4.00000   Marketing
26   1027      Ajay Sharma  95000.0             12.00000          IT
27   1028      Bhavana Rao  61000.0              6.00000     Finance
28   1029     Chirag Patel  74000.0              8.00000  Operations
29   1030       Ishita Sen  48000.0              2.00000          HR
30   1002      Priya Reddy  52000.0              5.00000          HR
31   1006     Anjali Gupta  70000.0              7.00000  Operations
32   1011      Arjun Mehta  62000.0              6.00000  Operations

In [28]:
df['name']=df['name'].str.lower()

In [29]:
df.head()

   empid          name   salary  years_of_experience department
0   1001  rahul sharma  45000.0                  3.0         IT
1   1002   priya reddy  52000.0                  5.0         HR
2   1003    amit kumar  60000.0                  6.0    Finance
3   1004       unknown  48000.0                  2.0  Marketing
4   1005     kiran rao  55000.0                  4.0         IT

In [30]:
df.drop_duplicates(inplace=True)

In [32]:
df[df["department"] == "IT"]

    empid            name   salary  years_of_experience department
0    1001    rahul sharma  45000.0                  3.0         IT
4    1005       kiran rao  55000.0                  4.0         IT
13   1014    divya kapoor  58000.0                  5.0         IT
18   1019  naveen chandra  72000.0                  8.0         IT
21   1022   nisha agarwal  59000.0                  5.0         IT
26   1027     ajay sharma  95000.0                 12.0         IT

In [33]:
df[df['salary']>70000]

    empid            name   salary  years_of_experience  department
8    1009      vikram das  80000.0              9.00000  Operations
12   1013    suresh yadav  85000.0              5.65625     Finance
16   1017     rakesh jain  90000.0             11.00000     Finance
18   1019  naveen chandra  72000.0              8.00000          IT
22   1023    harish kumar  78000.0              9.00000     Finance
26   1027     ajay sharma  95000.0             12.00000          IT
28   1029    chirag patel  74000.0              8.00000  Operations

In [34]:
df[df['years_of_experience']>5]

    empid            name   salary  years_of_experience  department
2    1003      amit kumar  60000.0              6.00000     Finance
5    1006    anjali gupta  70000.0              7.00000  Operations
6    1007     rohit verma  59500.0              8.00000     Finance
8    1009      vikram das  80000.0              9.00000  Operations
10   1011     arjun mehta  62000.0              6.00000  Operations
12   1013    suresh yadav  85000.0              5.65625     Finance
14   1015     manoj reddy  68000.0              7.00000  Operations
16   1017     rakesh jain  90000.0             11.00000     Finance
18   1019  naveen chandra  72000.0              8.00000          IT
20   1021      tarun babu  64000.0              6.00000  Operations
22   1023    harish kumar  78000.0              9.00000     Finance
24   1025    varun mishra  67000.0              7.00000  Operations
26   1027     ajay sharma  95000.0             12.00000          IT
27   1028     bhavana rao  61000.0              6.00000     Finance
28   1029    chirag patel  74000.0              8.00000  Operations

In [37]:
df[(df["department"] == "IT") | (df["department"] == "Finance")]

    empid            name   salary  years_of_experience department
0    1001    rahul sharma  45000.0              3.00000         IT
2    1003      amit kumar  60000.0              6.00000    Finance
4    1005       kiran rao  55000.0              4.00000         IT
6    1007     rohit verma  59500.0              8.00000    Finance
12   1013    suresh yadav  85000.0              5.65625    Finance
13   1014    divya kapoor  58000.0              5.00000         IT
16   1017     rakesh jain  90000.0             11.00000    Finance
18   1019  naveen chandra  72000.0              8.00000         IT
21   1022   nisha agarwal  59000.0              5.00000         IT
22   1023    harish kumar  78000.0              9.00000    Finance
26   1027     ajay sharma  95000.0             12.00000         IT
27   1028     bhavana rao  61000.0              6.00000    Finance

In [38]:
df[(df['salary']>60000) & (df['salary']<80000)]

    empid            name   salary  years_of_experience  department
5    1006    anjali gupta  70000.0                  7.0  Operations
10   1011     arjun mehta  62000.0                  6.0  Operations
14   1015     manoj reddy  68000.0                  7.0  Operations
18   1019  naveen chandra  72000.0                  8.0          IT
20   1021      tarun babu  64000.0                  6.0  Operations
22   1023    harish kumar  78000.0                  9.0     Finance
24   1025    varun mishra  67000.0                  7.0  Operations
27   1028     bhavana rao  61000.0                  6.0     Finance
28   1029    chirag patel  74000.0                  8.0  Operations

In [42]:
df.groupby("department").size()

department
Finance       6
HR            6
IT            6
Marketing     5
Operations    7
dtype: int64

In [44]:
df.groupby("department")["salary"].sum()

department
Finance       433500.0
HR            300500.0
IT            384000.0
Marketing     250500.0
Operations    485000.0
Name: salary, dtype: float64

In [46]:
df.groupby("department")["salary"].agg(['mean','max','min','sum'])

                    mean      max      min       sum
department
Finance     72250.000000  90000.0  59500.0  433500.0
HR          50083.333333  54000.0  47000.0  300500.0
IT          64000.000000  95000.0  45000.0  384000.0
Marketing   50100.000000  53000.0  46000.0  250500.0
Operations  69285.714286  80000.0  62000.0  485000.0

In [47]:
pivot=pd.pivot_table(df,index='department',values='salary',aggfunc='mean')
pivot

                  salary
department
Finance     72250.000000
HR          50083.333333
IT          64000.000000
Marketing   50100.000000
Operations  69285.714286