In [ ]:
import pandas as pd
df=pd.read_csv('/content/students_dataset.csv')
df

       name  age  marks department   exam_date
0     Rahul   21     88        CSE  2026-05-10
1     Priya   20     92        CSE  2026-05-10
2      Amit   22     76        EEE  2026-05-11
3     Sneha   21     85        ECE  2026-05-11
4     Kiran   20     79       MECH  2026-05-12
5    Anjali   22     91        CSE  2026-05-12
6     Rohit   21     73      CIVIL  2026-05-13
7     Pooja   20     87        ECE  2026-05-13
8    Vikram   23     68        EEE  2026-05-14
9      Neha   21     95        CSE  2026-05-14
10    Arjun   22     81       MECH  2026-05-15
11    Kavya   20     89        ECE  2026-05-15
12   Suresh   21     77      CIVIL  2026-05-16
13    Divya   22     93        CSE  2026-05-16
14    Manoj   20     72        EEE  2026-05-17
15    Meena   21     84        ECE  2026-05-17
16   Rakesh   23     69       MECH  2026-05-18
17   Shreya   22     90        CSE  2026-05-18
18   Naveen   20     78      CIVIL  2026-05-19
19     Asha   21     86        ECE  2026-05-19
20    Tarun   22     82        EEE  2026-05-20
21    Nisha   20     94        CSE  2026-05-20
22   Harish   21     75       MECH  2026-05-21
23  Deepika   22     88        ECE  2026-05-21
24    Varun   23     80      CIVIL  2026-05-22

In [ ]:
df[df['marks']>80]

       name  age  marks department   exam_date
0     Rahul   21     88        CSE  2026-05-10
1     Priya   20     92        CSE  2026-05-10
3     Sneha   21     85        ECE  2026-05-11
5    Anjali   22     91        CSE  2026-05-12
7     Pooja   20     87        ECE  2026-05-13
9      Neha   21     95        CSE  2026-05-14
10    Arjun   22     81       MECH  2026-05-15
11    Kavya   20     89        ECE  2026-05-15
13    Divya   22     93        CSE  2026-05-16
15    Meena   21     84        ECE  2026-05-17
17   Shreya   22     90        CSE  2026-05-18
19     Asha   21     86        ECE  2026-05-19
20    Tarun   22     82        EEE  2026-05-20
21    Nisha   20     94        CSE  2026-05-20
23  Deepika   22     88        ECE  2026-05-21

In [ ]:
df.sort_values(by='marks',ascending=False)

       name  age  marks department   exam_date
9      Neha   21     95        CSE  2026-05-14
21    Nisha   20     94        CSE  2026-05-20
13    Divya   22     93        CSE  2026-05-16
1     Priya   20     92        CSE  2026-05-10
5    Anjali   22     91        CSE  2026-05-12
17   Shreya   22     90        CSE  2026-05-18
11    Kavya   20     89        ECE  2026-05-15
23  Deepika   22     88        ECE  2026-05-21
0     Rahul   21     88        CSE  2026-05-10
7     Pooja   20     87        ECE  2026-05-13
19     Asha   21     86        ECE  2026-05-19
3     Sneha   21     85        ECE  2026-05-11
15    Meena   21     84        ECE  2026-05-17
20    Tarun   22     82        EEE  2026-05-20
10    Arjun   22     81       MECH  2026-05-15
24    Varun   23     80      CIVIL  2026-05-22
4     Kiran   20     79       MECH  2026-05-12
18   Naveen   20     78      CIVIL  2026-05-19
12   Suresh   21     77      CIVIL  2026-05-16
2      Amit   22     76        EEE  2026-05-11
22   Harish   21     75       MECH  2026-05-21
6     Rohit   21     73      CIVIL  2026-05-13
14    Manoj   20     72        EEE  2026-05-17
16   Rakesh   23     69       MECH  2026-05-18
8    Vikram   23     68        EEE  2026-05-14

In [ ]:
grades=[]
for mark in df['marks']:
  if mark>=90:
    grades.append('A')
  elif mark>=80:
    grades.append('B')
  elif mark>=70:
    grades.append('C')
  elif mark>=60:
    grades.append('D')
  else:
    grades.append('F')
df['grades']=grades
df

       name  age  marks department   exam_date grades
0     Rahul   21     88        CSE  2026-05-10      B
1     Priya   20     92        CSE  2026-05-10      A
2      Amit   22     76        EEE  2026-05-11      C
3     Sneha   21     85        ECE  2026-05-11      B
4     Kiran   20     79       MECH  2026-05-12      C
5    Anjali   22     91        CSE  2026-05-12      A
6     Rohit   21     73      CIVIL  2026-05-13      C
7     Pooja   20     87        ECE  2026-05-13      B
8    Vikram   23     68        EEE  2026-05-14      D
9      Neha   21     95        CSE  2026-05-14      A
10    Arjun   22     81       MECH  2026-05-15      B
11    Kavya   20     89        ECE  2026-05-15      B
12   Suresh   21     77      CIVIL  2026-05-16      C
13    Divya   22     93        CSE  2026-05-16      A
14    Manoj   20     72        EEE  2026-05-17      C
15    Meena   21     84        ECE  2026-05-17      B
16   Rakesh   23     69       MECH  2026-05-18      D
17   Shreya   22     90        CSE  2026-05-18      A
18   Naveen   20     78      CIVIL  2026-05-19      C
19     Asha   21     86        ECE  2026-05-19      B
20    Tarun   22     82        EEE  2026-05-20      B
21    Nisha   20     94        CSE  2026-05-20      A
22   Harish   21     75       MECH  2026-05-21      C
23  Deepika   22     88        ECE  2026-05-21      B
24    Varun   23     80      CIVIL  2026-05-22      B

In [ ]:
df["name"]=df['name'].str.upper()
df

       name  age  marks department   exam_date grades
0     RAHUL   21     88        CSE  2026-05-10      B
1     PRIYA   20     92        CSE  2026-05-10      A
2      AMIT   22     76        EEE  2026-05-11      C
3     SNEHA   21     85        ECE  2026-05-11      B
4     KIRAN   20     79       MECH  2026-05-12      C
5    ANJALI   22     91        CSE  2026-05-12      A
6     ROHIT   21     73      CIVIL  2026-05-13      C
7     POOJA   20     87        ECE  2026-05-13      B
8    VIKRAM   23     68        EEE  2026-05-14      D
9      NEHA   21     95        CSE  2026-05-14      A
10    ARJUN   22     81       MECH  2026-05-15      B
11    KAVYA   20     89        ECE  2026-05-15      B
12   SURESH   21     77      CIVIL  2026-05-16      C
13    DIVYA   22     93        CSE  2026-05-16      A
14    MANOJ   20     72        EEE  2026-05-17      C
15    MEENA   21     84        ECE  2026-05-17      B
16   RAKESH   23     69       MECH  2026-05-18      D
17   SHREYA   22     90        CSE  2026-05-18      A
18   NAVEEN   20     78      CIVIL  2026-05-19      C
19     ASHA   21     86        ECE  2026-05-19      B
20    TARUN   22     82        EEE  2026-05-20      B
21    NISHA   20     94        CSE  2026-05-20      A
22   HARISH   21     75       MECH  2026-05-21      C
23  DEEPIKA   22     88        ECE  2026-05-21      B
24    VARUN   23     80      CIVIL  2026-05-22      B

In [ ]:
df=df.drop(columns='department')
df

       name  age  marks   exam_date grades
0     RAHUL   21     88  2026-05-10      B
1     PRIYA   20     92  2026-05-10      A
2      AMIT   22     76  2026-05-11      C
3     SNEHA   21     85  2026-05-11      B
4     KIRAN   20     79  2026-05-12      C
5    ANJALI   22     91  2026-05-12      A
6     ROHIT   21     73  2026-05-13      C
7     POOJA   20     87  2026-05-13      B
8    VIKRAM   23     68  2026-05-14      D
9      NEHA   21     95  2026-05-14      A
10    ARJUN   22     81  2026-05-15      B
11    KAVYA   20     89  2026-05-15      B
12   SURESH   21     77  2026-05-16      C
13    DIVYA   22     93  2026-05-16      A
14    MANOJ   20     72  2026-05-17      C
15    MEENA   21     84  2026-05-17      B
16   RAKESH   23     69  2026-05-18      D
17   SHREYA   22     90  2026-05-18      A
18   NAVEEN   20     78  2026-05-19      C
19     ASHA   21     86  2026-05-19      B
20    TARUN   22     82  2026-05-20      B
21    NISHA   20     94  2026-05-20      A
22   HARISH   21     75  2026-05-21      C
23  DEEPIKA   22     88  2026-05-21      B
24    VARUN   23     80  2026-05-22      B

In [ ]:
df.drop(index=3)

       name  age  marks department   exam_date grades
0     RAHUL   21     88        CSE  2026-05-10      B
1     PRIYA   20     92        CSE  2026-05-10      A
2      AMIT   22     76        EEE  2026-05-11      C
4     KIRAN   20     79       MECH  2026-05-12      C
5    ANJALI   22     91        CSE  2026-05-12      A
6     ROHIT   21     73      CIVIL  2026-05-13      C
7     POOJA   20     87        ECE  2026-05-13      B
8    VIKRAM   23     68        EEE  2026-05-14      D
9      NEHA   21     95        CSE  2026-05-14      A
10    ARJUN   22     81       MECH  2026-05-15      B
11    KAVYA   20     89        ECE  2026-05-15      B
12   SURESH   21     77      CIVIL  2026-05-16      C
13    DIVYA   22     93        CSE  2026-05-16      A
14    MANOJ   20     72        EEE  2026-05-17      C
15    MEENA   21     84        ECE  2026-05-17      B
16   RAKESH   23     69       MECH  2026-05-18      D
17   SHREYA   22     90        CSE  2026-05-18      A
18   NAVEEN   20     78      CIVIL  2026-05-19      C
19     ASHA   21     86        ECE  2026-05-19      B
20    TARUN   22     82        EEE  2026-05-20      B
21    NISHA   20     94        CSE  2026-05-20      A
22   HARISH   21     75       MECH  2026-05-21      C
23  DEEPIKA   22     88        ECE  2026-05-21      B
24    VARUN   23     80      CIVIL  2026-05-22      B

In [ ]:
df.groupby('department')['marks'].mean()

department
CIVIL    77.000000
CSE      91.857143
ECE      86.500000
EEE      74.500000
MECH     76.000000
Name: marks, dtype: float64

In [ ]:
df1=df['marks'].agg(['sum','mean','max','min','median','std'])
print(df1)

sum       2072.000000
mean        82.880000
max         95.000000
min         68.000000
median      84.000000
std          7.959899
Name: marks, dtype: float64

In [ ]:
df2={'name':['Teja','Divya'],'age':[20,21],'marks':[87,91],'department':['CSE','ECE']}
pd.concat([df,pd.DataFrame(df2)])

       name  age  marks department   exam_date grades
0     RAHUL   21     88        CSE  2026-05-10      B
1     PRIYA   20     92        CSE  2026-05-10      A
2      AMIT   22     76        EEE  2026-05-11      C
3     SNEHA   21     85        ECE  2026-05-11      B
4     KIRAN   20     79       MECH  2026-05-12      C
5    ANJALI   22     91        CSE  2026-05-12      A
6     ROHIT   21     73      CIVIL  2026-05-13      C
7     POOJA   20     87        ECE  2026-05-13      B
8    VIKRAM   23     68        EEE  2026-05-14      D
9      NEHA   21     95        CSE  2026-05-14      A
10    ARJUN   22     81       MECH  2026-05-15      B
11    KAVYA   20     89        ECE  2026-05-15      B
12   SURESH   21     77      CIVIL  2026-05-16      C
13    DIVYA   22     93        CSE  2026-05-16      A
14    MANOJ   20     72        EEE  2026-05-17      C
15    MEENA   21     84        ECE  2026-05-17      B
16   RAKESH   23     69       MECH  2026-05-18      D
17   SHREYA   22     90        CSE  2026-05-18      A
18   NAVEEN   20     78      CIVIL  2026-05-19      C
19     ASHA   21     86        ECE  2026-05-19      B
20    TARUN   22     82        EEE  2026-05-20      B
21    NISHA   20     94        CSE  2026-05-20      A
22   HARISH   21     75       MECH  2026-05-21      C
23  DEEPIKA   22     88        ECE  2026-05-21      B
24    VARUN   23     80      CIVIL  2026-05-22      B
0      Teja   20     87        CSE         NaN    NaN
1     Divya   21     91        ECE         NaN    NaN

In [ ]:
df['exam_date']=pd.to_datetime(df['exam_date'])
df['day']=df['exam_date'].dt.day
df['month']=df['exam_date'].dt.month
df['year']=df['exam_date'].dt.year
print(df[['exam_date','day','month','year']])

    exam_date  day  month  year
0  2026-05-10   10      5  2026
1  2026-05-10   10      5  2026
2  2026-05-11   11      5  2026
3  2026-05-11   11      5  2026
4  2026-05-12   12      5  2026
5  2026-05-12   12      5  2026
6  2026-05-13   13      5  2026
7  2026-05-13   13      5  2026
8  2026-05-14   14      5  2026
9  2026-05-14   14      5  2026
10 2026-05-15   15      5  2026
11 2026-05-15   15      5  2026
12 2026-05-16   16      5  2026
13 2026-05-16   16      5  2026
14 2026-05-17   17      5  2026
15 2026-05-17   17      5  2026
16 2026-05-18   18      5  2026
17 2026-05-18   18      5  2026
18 2026-05-19   19      5  2026
19 2026-05-19   19      5  2026
20 2026-05-20   20      5  2026
21 2026-05-20   20      5  2026
22 2026-05-21   21      5  2026
23 2026-05-21   21      5  2026
24 2026-05-22   22      5  2026

In [ ]:
indexed_df=df.set_index("name")
print(indexed_df.loc['RAHUL'])

age                            21
marks                          88
department                    CSE
exam_date     2026-05-10 00:00:00
grades                          B
day                            10
month                           5
year                         2026
Name: RAHUL, dtype: object

In [ ]:
pivot=pd.pivot_table(df,values='marks',index='department',aggfunc='mean')
print(pivot)